# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Bousai Info

on:
  repository_dispatch:
    types: [on-demand-bousai]
#  schedule:
#    - cron:  '5 */4 * * *'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f dam_req.txt ]; then pip install -r bousai_req.txt; fi
        sudo apt install fonts-noto
    - name: Run script
      run: |
        python bousai.py
      env:
        IMABARI_CK: ${{ secrets.IMABARI_CK }}
        IMABARI_CS: ${{ secrets.IMABARI_CS }}
        IMABARI_AT: ${{ secrets.IMABARI_AT }}
        IMABARI_AS: ${{ secrets.IMABARI_AS }}
