# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Traffic Control

on:
  repository_dispatch:
    types: [on-demand-test]
  schedule:
    - cron:  '0 13 4,9,14,19,24,29 * *'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f traffic_control.txt ]; then pip install -r traffic_control.txt; fi
    - name: Run script
      run: |
        python traffic_control.py
      env:
        IMABARI_CK: ${{ secrets.IMABARI_CK }}
        IMABARI_CS: ${{ secrets.IMABARI_CS }}
        IMABARI_AT: ${{ secrets.IMABARI_AT }}
        IMABARI_AS: ${{ secrets.IMABARI_AS }}
